---
title: "Sector_Markdown"
author: "Mohagoney Moore"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#This is the Markdown version of the same code


#Load Sector Data
data = read.csv("C:/Users/15109/Desktop/Financial Research (Andrey)/Industry_Sector_Research/Industry_Sector_Data/SPTsectors.csv")

SPT = data[,-1]

#Each sector of equal weight
w = 1/11

```


```{r}
#No re-balance 

N = nrow(SPT) #246 months
C = ncol(SPT) #11 sectors

sector_sums = vector(mode = "numeric")

#for loop that gathers the total wealth of the sectors
for(sectors in 1:C){
  
  sector_sums[sectors] = exp(sum(SPT[1:N,sectors]))
  
}


total_monthly_average = w * log(sum(sector_sums,na.rm=TRUE))
total_monthly_average



```


```{r}

#This code re-balances an equally weighted portfolio of different sectors returns. Please enter how often you would like your portfolio re-balanced in T. 

T = 1 #Enter in period (in months)
TOTAL = nrow(SPT) #246 Months (20.5 Years)
C = ncol(SPT) #11 sectors
N =  TOTAL/T #number of periods
#------------------------------------------------

#data frame for weighted return per sector (per period)
weighted_return = as.data.frame(matrix(0, nrow = N, ncol = 1)) 

#data frame for periodic return in portfolio
periodic_sum = as.data.frame(matrix(0, nrow = N, ncol = 1)) 

#data frame for periodic wealth generated
periodic_wealth = as.data.frame(matrix(0, nrow = N, ncol = 1))

#data frame for the periodic return (the first 20 values are used to estimate mu and sd).
periodic_return = as.data.frame(matrix(0, nrow = N, ncol = 1))

#-----------------------------------------

for(period in 1:N){
    for(sector in 1:C){
  
    time1 = T * (period - 1) + 1
    time2 = T * period
    
    #Stores the weighted returns of the sector portfolio for each period
    weighted_return[period,sector] = w * exp(sum(SPT[time1:time2, sector]))
    
    #Stores the sum of each weighted return in the portfolio
    
    periodic_sum[period,] = sum(weighted_return[period,])

    }  
}

  
#--------------------------------------------

#Stores the periodic wealth for the portfolio

#initial value for months
m_n = periodic_sum[1,] # sum for month 1
periodic_wealth[1,] = m_n
w_n = m_n


for(period in 2:N){
  #periodic wealth
  w_n = w_n * periodic_sum[period,]
  periodic_wealth[period,1] = w_n
  
}

#-----------------------------------------------
#Stores Average Periodic Return 

#Period 1 return 
p_1 = log(periodic_wealth[1,])
periodic_return[1,1] = p_1

#for loop that gathers periodic wealth from wealth data frame
for(period in 2:N){
  
  wealth1 = period - 1 
  wealth2 = period
  
  periodic_return[period,1] = log((periodic_wealth[wealth2,]/periodic_wealth[wealth1,]))
  
}

mean_return = mean(periodic_return[1:20,])
sd_return = sd(periodic_return[1:20,])

```

